openapi: 3.0.0
info:
  title: AI-Powered Personal Assistant API
  description: API for a personal assistant that manages tasks with advanced prioritization, time tracking, and estimation features.
  version: "1.0.0"
  contact:
    email: support@your-assistant-app.com
servers:
  - url: http://localhost:7071/api
    description: Production server
paths:
  /tasks:
    get:
      summary: List all tasks
      operationId: listTasks
      responses:
        '200':
          description: An array of prioritized tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Add a new task with estimation
      operationId: addTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTask'
      responses:
        '201':
          description: Task created
  /tasks/{taskId}:
    get:
      summary: Get a specific task
      operationId: getTask
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    put:
      summary: Update a task
      operationId: updateTask
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTask'
      responses:
        '200':
          description: Task updated
    delete:
      summary: Delete a task
      operationId: deleteTask
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Task deleted
components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - priority
        - estimatedTime
        - dueDate
        - isComplete
        - createdAt
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        priority:
          type: string
          enum: [Low, Medium, High, Urgent]
        estimatedTime:
          type: integer
          description: Estimated time in minutes
        dueDate:
          type: string
          format: date-time
        isComplete:
          type: boolean
        createdAt:
          type: string
          format: date-time
    NewTask:
      type: object
      required:
        - title
        - estimatedTime
      properties:
        title:
          type: string
        description:
          type: string
        estimatedTime:
          type: integer
          description: Estimated time in minutes
        dueDate:
          type: string
          format: date-time
    UpdateTask:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        priority:
          type: string
          enum: [Low, Medium, High, Urgent]
        estimatedTime:
          type: integer
          description: Estimated time in minutes
        isComplete:
          type: boolean