openapi: 3.0.1
info:
  title: Azure Functions Todo Assistant API
  version: "1.0.0"
  description: API for managing tasks in a Todo Assistant application.
  contact:
    name: Todo Assistant API Support
    email: support@todoassistant.com
servers:
  - url: https://todoassistant.azurewebsites.net/api
paths:
  /tasks/{category}:
    get:
      summary: List all tasks for a user
      operationId: listUserTasks
      parameters:
        - name: category
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: An array of tasks for the specified user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoTask'

  /tasks:
    post:
      summary: Add a new task
      operationId: addNewTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTaskRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoTask'

  /tasks/{category}/{taskId}:
    get:
      summary: Get a specific task
      operationId: getSpecificTask
      parameters:
        - name: category
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details of the specified task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoTask'

    put:
      summary: Update a specific task
      operationId: updateSpecificTask
      parameters:
        - name: category
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Task updated successfully

    delete:
      summary: Delete a specific task
      operationId: deleteSpecificTask
      parameters:
        - name: category
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Task deleted successfully

components:
  schemas:
    TodoTask:
      type: object
      properties:
        PartitionKey:
          type: string
        RowKey:
          type: string
        Title:
          type: string
        Description:
          type: string
        Priority:
          type: string
        EstimatedTime:
          type: integer
        DueDate:
          type: string
          format: date-time
        IsComplete:
          type: boolean
        CreatedAt:
          type: string
          format: date-time
    NewTaskRequest:
      type: object
      properties:
        PartitionKey:
          type: string
        Title:
          type: string
        Description:
          type: string
        Priority:
          type: string
        EstimatedTime:
          type: integer
        DueDate:
          type: string
          format: date-time
        IsComplete:
          type: boolean
    UpdateTaskRequest:
      type: object
      properties:
        PartitionKey:
          type: string
        RowKey:
          type: string
        Title:
          type: string
        Description:
          type: string
        Priority:
          type: string
        EstimatedTime:
          type: integer
        DueDate:
          type: string
          format: date-time
        IsComplete:
          type: boolean
