name: .NET Build, Test, and Deploy

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
    
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-restore

    - name: 'Resolve Project Dependencies Using Dotnet'
    shell: bash
    run: |
      pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
      dotnet build --configuration Release --output ./output
      popd

    - name: 'Run Azure Functions Action'
    uses: Azure/functions-action@v1
    id: fa
    with:
      app-name: 'todoAssistant'
      slot-name: 'Production'
      package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
      publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
